# This macro is used to properly set up the interactive session (GUI)

/vis/open OGLI
#/vis/open QGL


/gui/addMenu vis Visualization
/gui/addButton vis "Draw Axes" "/vis/scene/add/axes 0 0 0 1 m"

/gui/addMenu run Run
/gui/addButton run "Beam On (1)" "/run/beamOn 1"
/gui/addButton run "Beam On (10)" "/run/beamOn 10"
/gui/addButton run "Beam On (100)" "/run/beamOn 100"
/gui/addButton run "Beam On (1000)" "/run/beamOn 1000"
/gui/addButton run "Beam On (10000)" "/run/beamOn 10000"

#/Physics/addPhysics QGSP_BERT_HP

/run/initialize
/vis/drawVolume
/vis/scene/add/trajectories smooth rich
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByParticleID e- green
/vis/modeling/trajectories/create/drawByParticleID e+ cyan
/vis/modeling/trajectories/create/drawByParticleID proton red
/vis/modeling/trajectories/create/drawByParticleID gamma blue
/vis/modeling/trajectories/create/drawByParticleID neutron yellow
/vis/modeling/trajectories/create/drawByParticleID alpha purple
/vis/modeling/trajectories/create/drawByParticleID pi+ magenta
/vis/modeling/trajectories/create/drawByParticleID pi- magenta
/vis/modeling/trajectories/create/drawByParticleID pi0 magenta

/vis/viewer/flush

#/tracking/verbose 2
